name: Flujo de trabajo para dev

on:
  push:
    branches:
      - 'dev/**' # Esto se activar치 en cualquier rama hija de dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Crear PR para dev
        if: "contains(github.event.head_commit.message, 'feat')" # Si el commit es de tipo feat
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev" # Rama a la que se fusionar치
          pr_title: "PR autom치tico para dev"
          pr_body: "Este es un PR autom치tico creado por GitHub Actions."
          pr_label: "automerge" # Etiqueta para el PR
          github_token: ${{ secrets.GH_TOKEN }}
