name: Flujo de trabajo para ramas de características

on:
  push:
    branches-ignore:
      - 'main'
      - 'beta'
      - 'dev'
      - 'fix'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Crear PR para dev o fix
        uses: repo-sync/pull-request@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          pr_label: "automerge" # Etiqueta para el PR
          pr_title: "PR automático"
          pr_body: "Este es un PR automático creado por GitHub Actions."
          destination_branch: >-
            ${{ contains(github.event.head_commit.message, 'fix') && (startsWith(github.ref, 'refs/heads/hotfix') || startsWith(github.ref, 'refs/heads/bugfix')) ? 'fix' : 'dev' }}
