name: workflow para ramas de características y fixes

on:
  push:
    branches-ignore:
      - 'main'
      - 'beta'
      - 'dev'
      - 'fix'

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Crear PR para dev o fix
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $*; }
          if [[ "${{ github.event.head_commit.message }}" == *"fix"* && ("${{ github.ref }}" == refs/heads/hotfix/* || "${{ github.ref }}" == refs/heads/bugfix/*) ]]; then
            gh_pr_up --title "PR automático" --body "Este es un PR automático creado por GitHub Actions." --base 'fix'
          elif [[ "${{ github.event.head_commit.message }}" == *"feat"* ]]; then
            gh_pr_up --title "PR automático" --body "Este es un PR automático creado por GitHub Actions." --base 'dev'
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
