name: Notify When Branch is Merged

on:
  merge_group:
    branches:
      - main
  pull_request:
    types: [opened, closed, reopened, merged]
  push:
    branches-ignore:
      - 'main'
  delete:
    branches: ['*']

jobs:
  msg:
    name: Sending Message
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Info
        id: pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_CREATOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "PR_CREATOR_IMAGE=${{ github.event.pull_request.user.avatar_url }}" >> $GITHUB_ENV
          echo "PR_STATE=${{ github.event.pull_request.state }}" >> $GITHUB_ENV
          echo "PR_URL=https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "PR_FROM_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "PR_TO_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "TIME=$(TZ=America/Argentina/Buenos_Aires date +'%a, %d %b %Y %H:%M')" >> $GITHUB_ENV
          if [ "${{ github.event.pull_request.state }}" = "open" ]; then
            echo "PR_STATE_EMOJI=🟢" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "PR_STATE=merged" >> $GITHUB_ENV
            echo "PR_STATE_EMOJI=🟣" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.state }}" = "closed" ]; then
            echo "PR_STATE_EMOJI=🔴" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.state }}" = "reopened" ]; then
            echo "PR_STATE_EMOJI=🟠" >> $GITHUB_ENV
          fi

      - name: Send PR Message to Slack
        if: github.event_name == 'pull_request'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "#36a64f",
                "author_name": "GitHub Actions",
                "author_icon": "https://github.githubassets.com/images/modules/logos_page/Octocat.png",
                "title": "Pull Request Notification from GitHub",
                "text": "*${{ env.PR_CREATOR }}* created a new pull request in *${{ env.REPO }}*",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ env.REPO }}",
                    "short": true
                  },
                  {
                    "title": "PR ID",
                    "value": "<${{ env.PR_URL }}|#${{ env.PR_NUMBER }}>",
                    "short": true
                  },
                  {
                    "title": "Title",
                    "value": "${{ env.PR_TITLE }}",
                    "short": true
                  },
                  {
                    "title": "State",
                    "value": "${{ env.PR_STATE }} ${{ env.PR_STATE_EMOJI }}",
                    "short": true
                  },
                  {
                    "title": "From",
                    "value": "${{ env.PR_FROM_BRANCH }}",
                    "short": true
                  },
                  {
                    "title": "To",
                    "value": "${{ env.PR_TO_BRANCH }}",
                    "short": true
                  },
                  {
                    "title": "Time",
                    "value": "${{ env.TIME }}",
                    "short": true
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  check_direct_push:
    name: Check for Direct Push to Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Check if direct push to main
        if: github.event.ref == 'refs/heads/main'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "#ed1e45",
                "author_name": "GitHub Actions",
                "title": "Direct Push to Main Branch Detected",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Pusher",
                    "value": "${{ github.actor }}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "main",
                    "short": true
                  },
                  {
                    "title": "Time",
                    "value": "$(TZ=America/Argentina/Buenos_Aires date +'%a, %d %b %Y %H:%M')",
                    "short": true
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_branch_deleted:
    name: Notify Branch Deletion
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        if: github.event_name == 'delete'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "#ed1e45",
                "author_name": "GitHub Actions",
                "title": "Branch Deletion Notification",
                "text": ":warning: Branch `${{ github.event.ref }}` has been deleted by `${{ github.actor }}`",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "User",
                    "value": "${{ github.actor }}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "${{ github.ref }}",
                    "short": true
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
