name: Notify When Branch is Merged

on:
  merge_group: 
    branches: 
      - main
  pull_request:
    types: [opened, closed, reopened]

jobs:
  msg:
    name: Sending Message
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Info
        id: pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_CREATOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "PR_STATE=${{ github.event.pull_request.state }}" >> $GITHUB_ENV
          echo "PR_URL=https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "TIME=$(TZ=America/Argentina/Buenos_Aires date -u +'%a, %d %b %Y %H:%M:%S GMT')" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV

      - name: Send PR Message to Slack
        if: github.event_name == 'pull_request'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Pull Request Notification*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ env.REPO }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*PR ID:*\n<${{ env.PR_URL }}|#${{ env.PR_NUMBER }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Title:*\n${{ env.PR_TITLE }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Created by:*\n${{ env.PR_CREATOR }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*State:*\n${{ env.PR_STATE }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Time:*\n${{ env.TIME }}"
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Check for Direct Push to Main Branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Warning: Direct Push to Main Branch*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Pushed by:*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Time:*\n$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit URL:*\n<${{ github.event.head_commit.url }}|View Commit>"
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
