name: Notify When Branch is Merged

on:
  merge_group: 
    branches: 
      - main
  pull_request:
    types: [opened, closed, reopened, merged]
  push:
    branches-ignore:
      - 'main'
  delete:
    branches: ['*']

jobs:
  msg:
    name: Sending Message
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Info
        id: pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_CREATOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "PR_CREATOR_IMAGE=${{ github.event.pull_request.user.avatar_url }}" >> $GITHUB_ENV
          echo "PR_STATE=${{ github.event.pull_request.state }}" >> $GITHUB_ENV
          echo "PR_URL=https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "PR_FROM_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "PR_TO_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "TIME=$(TZ=America/Argentina/Buenos_Aires date +'%a, %d %b %Y %H:%M')" >> $GITHUB_ENV
          if [ "${{ github.event.pull_request.state }}" = "open" ]; then
            echo "COLOR=#ffffff" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "COLOR=#36a64f" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.state }}" = "closed" ]; then
            echo "COLOR=#ed1e45" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.state }}" = "reopened" ]; then
            echo "COLOR=#ff6723" >> $GITHUB_ENV
          fi

      - name: Send PR Message to Slack
        if: github.event_name == 'pull_request'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "${{ env.COLOR }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Pull Request Notification from GitHub*"
                    }
                  },
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "image",
                        "image_url": "${{ env.PR_CREATOR_IMAGE }}",
                        "alt_text": "github user image"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*${{ env.PR_CREATOR }}* created a new pull request in *${{ env.REPO }}*"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Repository:*\n${{ env.REPO }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*PR ID:*\n<${{ env.PR_URL }}|#${{ env.PR_NUMBER }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Title:*\n${{ env.PR_TITLE }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*State:*\n${{ env.PR_STATE }} ${{ env.PR_STATE_EMOJI }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*From:*\n${{ env.PR_FROM_BRANCH }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*To:*\n${{ env.PR_TO_BRANCH }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Time:*\n${{ env.TIME }}"
                      }
                    ]
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  check_direct_push:
    name: Check for Direct Push to Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Check if direct push to main
        if: github.event.ref == 'refs/heads/main'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "#ed1e45",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Direct Push to Main Branch Detected*"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Repository:*\n${{ github.repository }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Pusher:*\n${{ github.actor }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Branch:*\nmain"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Time:*\n$(TZ=America/Argentina/Buenos_Aires date +'%a, %d %b %Y %H:%M')"
                      }
                    ]
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_branch_deleted:
    name: Notify Branch Deletion
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        if: github.event_name == 'delete'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "attachments": [
              {
                "color": "#ed1e45",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Branch Deletion Notification* \n:warning: Branch `${{ github.ref }}` has been deleted by `${{ github.actor }}`"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Repository:*\n${{ github.repository }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*User:*\n${{ github.actor }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Branch:*\n${{ github.ref }}"
                      }
                    ]
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
